language: node_js
node_js:
  - '8.0'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script: 'npm test'
after_success: 'npm run report-coverage'
